feat: remove swap polling
RampNetwork/ramp-instant-sdk pull request #14
Opened 2021-11-08 14:27 UTC by domkolasinski

2021-11-08 16:14 UTC, jakubsta requested changes

2021-11-08 16:14 UTC, jakubsta commented on src/ramp-instant-sdk.ts
> +    this._on(WidgetEventTypes.PURCHASE_CREATED, (event: IPurchaseCreatedEvent) => event, true);
```suggestion
```

2021-11-09 09:00 UTC, domkolasinski commented on src/ramp-instant-sdk.ts
> +    this._on(WidgetEventTypes.PURCHASE_CREATED, (event: IPurchaseCreatedEvent) => event, true);
Fixed.

2021-11-19 10:14 UTC, jakubsta approved these changes

2021-11-19 10:14 UTC, merged