chore: bump deps versions
RampNetwork/ramp-instant-sdk pull request #18
Opened 2021-12-10 09:17 UTC by jakubsta

2021-12-10 09:20 UTC, macbem requested changes

2021-12-10 09:20 UTC, macbem commented on package.json
>      "body-scroll-lock": "^2.6.4"
Why wasn't this one updated? There's a 4.0.0 beta and 3.x.x

2021-12-10 17:02 UTC, macbem approved these changes
If you tested the `body-scroll-lock` bump 😅 

Are there some TS compiler flags that we can make stricter?

2021-12-13 08:39 UTC, jakubsta commented
> If you tested the body-scroll-lock bump 😅

Yes, I've tested it but I'll ask Łukasz for additional tests before release.

> Are there some TS compiler flags that we can make stricter?

Unfortunately, I haven't had a chance/time to look at this 😞

2021-12-14 08:35 UTC, merged